"""Generate docs/TOOLS.md from FastMCP's runtime tool registry.

Walks every tool registered on ``build_server()`` and rewrites
``docs/TOOLS.md`` so the published reference can never drift from the code.

Usage::

    python -m ableton_mcp.scripts.generate_tools_doc
    python -m ableton_mcp.scripts.generate_tools_doc --out path/to/file.md

The output groups tools by category. The category is the first underscore-
separated chunk of the tool name (``track_set_volume`` → ``track``), with one
exception: tools whose first chunk is ``live`` are grouped under ``transport``
because that mirrors how the codebase organises them.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path
from typing import Any, Iterable

from ..server import build_server


# Map the prefix found in tool names to a human-friendly category title.
# Anything not in this map is title-cased automatically.
_PREFIX_TITLES: dict[str, str] = {
    "live": "Transport (live_*)",
    "track": "Tracks (track_*)",
    "clip": "Clips (clip_*)",
    "scene": "Scenes (scene_*)",
    "cue": "Cue points (cue_point_*)",
    "view": "View (view_*)",
    "arrangement": "Arrangement (arrangement_*)",
    "routing": "Routing (routing_*)",
    "device": "Devices (device_*)",
    "midi": "MIDI mapping & files (midi_*)",
    "audio": "Audio analysis (audio_*)",
    "listen": "Listeners (listen_*)",
    "op": "High-level operations (op_*)",
    "browser": "Browser (browser_*)",
    "render": "Render (render_*)",
    "sound": "Sound modeling (sound_*)",
    "ableton": "Knowledge / RAG (ableton_*)",
    "suno": "Suno (suno_*)",
}


def _category_for(tool_name: str) -> str:
    """Return the bucket key for a tool name."""
    head = tool_name.split("_", 1)[0]
    return head


def _category_title(key: str) -> str:
    return _PREFIX_TITLES.get(key, f"{key.title()} ({key}_*)")


def _format_type(schema: dict[str, Any]) -> str:
    """Render a JSONSchema type expression as a short string."""
    if "anyOf" in schema:
        return " | ".join(_format_type(s) for s in schema["anyOf"])
    if "enum" in schema:
        return "enum(" + ", ".join(repr(v) for v in schema["enum"]) + ")"
    t = schema.get("type")
    if t == "array":
        items = schema.get("items") or {}
        return f"array<{_format_type(items)}>" if items else "array"
    if t == "object":
        return "object"
    if isinstance(t, list):
        return " | ".join(t)
    if t is None:
        return "any"
    return str(t)


def _params_table(input_schema: dict[str, Any]) -> str:
    props: dict[str, Any] = input_schema.get("properties") or {}
    if not props:
        return "_No parameters._\n"
    required = set(input_schema.get("required") or [])
    rows = ["| Name | Type | Required | Default |", "|------|------|----------|---------|"]
    for pname, pschema in props.items():
        ptype = _format_type(pschema)
        req = "yes" if pname in required else "no"
        default = pschema.get("default", "")
        if default == "" and pname not in required:
            default = "—"
        if isinstance(default, str) and default not in ("—", ""):
            default = repr(default)
        rows.append(f"| `{pname}` | `{ptype}` | {req} | {default} |")
    return "\n".join(rows) + "\n"


def _render(tools: Iterable[Any]) -> str:
    by_cat: dict[str, list[Any]] = {}
    for t in sorted(tools, key=lambda x: x.name):
        by_cat.setdefault(_category_for(t.name), []).append(t)

    # Keep _PREFIX_TITLES order first, then any unknown prefixes alphabetically.
    order = [k for k in _PREFIX_TITLES if k in by_cat]
    order += sorted(k for k in by_cat if k not in _PREFIX_TITLES)

    lines: list[str] = []
    lines.append("# AbletonMCP tools reference")
    lines.append("")
    lines.append(
        "Auto-generated by `python -m ableton_mcp.scripts.generate_tools_doc`."
    )
    lines.append(" Do not hand-edit — your changes will be overwritten.")
    lines.append("")
    total = sum(len(v) for v in by_cat.values())
    lines.append(f"**{total} tools** across **{len(by_cat)} categories**.")
    lines.append("")

    # Table of contents
    lines.append("## Table of contents")
    lines.append("")
    for key in order:
        title = _category_title(key)
        anchor = title.lower().replace(" ", "-").replace("(", "").replace(")", "").replace("*", "").replace("/", "").replace("&", "").replace("--", "-").rstrip("-")
        lines.append(f"- [{title}](#{anchor}) — {len(by_cat[key])} tools")
    lines.append("")

    for key in order:
        title = _category_title(key)
        lines.append(f"## {title}")
        lines.append("")
        for tool in by_cat[key]:
            desc = (tool.description or "").strip() or "_(no description)_"
            lines.append(f"### `{tool.name}`")
            lines.append("")
            lines.append(desc)
            lines.append("")
            lines.append("**Parameters**")
            lines.append("")
            lines.append(_params_table(tool.inputSchema or {}))
            lines.append("")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


async def _collect_markdown() -> str:
    mcp = build_server()
    tools = await mcp.list_tools()
    return _render(tools)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path. Defaults to docs/TOOLS.md at the repo root.",
    )
    args = parser.parse_args(argv)

    if args.out is None:
        # repo_root = .../src/ableton_mcp/scripts/generate_tools_doc.py → up 4
        repo_root = Path(__file__).resolve().parents[3]
        out = repo_root / "docs" / "TOOLS.md"
    else:
        out = args.out

    out.parent.mkdir(parents=True, exist_ok=True)
    md = asyncio.run(_collect_markdown())
    out.write_text(md, encoding="utf-8")
    print(f"Wrote {out} ({md.count(chr(10)) + 1} lines, {len(md)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
